[project]
name = "pgfe"
description = "Pygame Framework Environent. A 2D game framework that is built ontop of pygame-ce!"
version = "0.1.0.post1"
requires-python = ">=3.14"
dependencies = [
    "pygame-ce",
]
authors = [
    {name = "Henry Watts", email = "ninesideddevelopment@gmail.com"}
]
readme = "README.md"

[build-system]
requires = ["uv_build>=0.12.9,<0.13"]
build-backend = "uv_build"
